# Generated by Django 3.2.9 on 2021-11-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('availability', models.BooleanField()),
                ('category', models.CharField(max_length=1000)),
                ('day', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]

# class Migration2(migrations.Migration):

#     initial = True

#     dependencies = [
#         ('hello', '0001_initial'),
#     ]

#     operations = [
#         migrations.CreateModel(
#             name='Time',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('day', models.CharField(max_length=1000)),
#                 ('date', models.DateField()),
#                 ('time', models.TimeField()),
#             ],
#         ),
#     ]
