# Generated by Django 3.2.9 on 2021-11-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('opening_time', models.CharField(max_length=1000)),
                ('closing_time', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
